# ScreenStreamerManager by YangHaitao
#
# configuration.yml
#

# LOG_LEVEL
# a value of (NOSET, DEBUG, INFO, WARNING, ERROR, CRITICAL)
# default NOSET
log_level: DEBUG

get_active_window: ./get_active_window

rtmp: ./rtmp
rtmp_config_path: ./configuration.rtmp.yml

mjpeg: ./mjpeg
mjpeg_config_path: ./configuration.mjpeg.yml
